[build]
  # Directory to publish (not needed if it's the root)
  publish = "/"
  # Directory with serverless functions
  functions = "functions"

# Handle redirects for single page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # This redirect rule should be commented out or removed if you're 
  # going to have multiple HTML pages in your site.
  # It's only needed for single-page applications.

# Set security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://js.stripe.com; script-src 'self' https://js.stripe.com 'unsafe-inline'; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' https://api.stripe.com;"