# Global build settings
[build]
  publish = "/"  # Your publish directory (adjust if needed for your setup)

# Handle any deploy previews - Force all redirects to the main domain
[[redirects]]
  from = "https://*--claudeappbuilder.netlify.app/*"
  to = "https://claudeappbuilder.netlify.app/:splat"
  status = 301
  force = true

# Handle specific redirection for success stories
[[redirects]]
  from = "https://*--claudeappbuilder.netlify.app/success-stories"
  to = "https://claudeappbuilder.netlify.app/success-stories"
  status = 301
  force = true

[[redirects]]
  from = "https://*--claudeappbuilder.netlify.app/success-stories.html"
  to = "https://claudeappbuilder.netlify.app/success-stories.html"
  status = 301
  force = true

[[redirects]]
  from = "https://*--claudeappbuilder.netlify.app/submit-success-story"
  to = "https://claudeappbuilder.netlify.app/submit-success-story"
  status = 301
  force = true

[[redirects]]
  from = "https://*--claudeappbuilder.netlify.app/submit-success-story.html"
  to = "https://claudeappbuilder.netlify.app/submit-success-story.html"
  status = 301
  force = true

# Handle extension-less URLs
[[redirects]]
  from = "/success-stories"
  to = "/success-stories.html"
  status = 301

[[redirects]]
  from = "/submit-success-story"
  to = "/submit-success-story.html"
  status = 301

[[redirects]]
  from = "/admin/success-stories"
  to = "/admin/success-stories.html"
  status = 301

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Set custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' https://identity.netlify.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://identity.netlify.com;"
    
# Post-processing settings
[build.processing]
  skip_processing = false
  
[build.processing.html]
  pretty_urls = true

# Context-specific settings
[context.production]
  command = ""  # Your build command if any
  
[context.deploy-preview]
  command = ""  # Your build command for deploy previews if any
