[build]
  # Directory to publish (not needed if it's the root)
  publish = "/"
  # Directory with serverless functions
  functions = "functions"
  # Uncomment this if you need dependencies installed during build
  # command = "cd functions && npm install"

# Configure Node bundler for functions
[functions]
  node_bundler = "esbuild"
  # Include node modules in function deployment
  included_files = ["functions/node_modules/**"]

# Set security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://js.stripe.com https://identity.netlify.com; script-src 'self' https://js.stripe.com https://identity.netlify.com 'unsafe-inline'; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' https://api.stripe.com https://identity.netlify.com;"
